#! /bin/bash

# ------------------------------------------
# Created by d8283, 2014.07.03 15:30
# Updated by d8283, 2014.07.04 12:00
#            d8283@gmail.com
#
# Project nagios-plugins:
#       https://github.com/d8283
# ------------------------------------------

      key="`echo $1 | tr '_' ' '`"
ipmi_info="/dev/shm/ipmi.info"

grep "^$key" $ipmi_info | awk -F '|' '{print $2}' | awk '{print $1}'

