#! /bin/bash

curl=/usr/local/curl/bin/curl
test -x $curl || curl=curl

es_host="http://192.168.10.7:9200"
port=80

# 因为时区的原因，当天8点以前的日志是存在前一天的索引中的
es_index="logstash-`date -d '483 minutes ago' +%Y.%m.%d`,logstash-`date -d '480 minutes ago' +%Y.%m.%d`"

query='{"size":0,"query":{"bool":{"filter":[{"range":{"@timestamp":{"gte":"now-3m","lte":"now-2m"}}}]}}}'
result=`curl -s --max-time 4 -XGET "$es_host/$es_index/_search?filter_path=hits.total" -d "$query"`

# 请求错误
if ! grep -q "total" <<< $result
then
    echo 0
    exit 0
fi

# 请求错误
if ! grep -Pq '"total"\s*:\s*\d+' <<< $result
then
    # 每天八点之后的数据会保存到新的索引，没有新数据时查询会报错
    if grep -q "index_not_found_exception" <<< $result && [ "`date -d '480 minutes ago' +%H`" = "00" ]
    then
        echo 10000
        exit 0
    fi

    echo 0
    exit 0
fi

grep -Po '\d+' <<< $result || echo 0
exit 0
